# -*- coding: utf-8 -*-
"""k_means_ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwDcw4v-QV6YdIRfv4vPOWz2MEB6yeto
"""

# Part 1 - Data Preprocessing

# Importing the libraries
import pandas as pd

# Importing the dataset
dataset = pd.read_csv("perfil_politico.csv")

dataset.head(  )

X = dataset.iloc[:,:].values
print("Primeiros 6 linhas do banco de dados:")
print(X[0:6,:])

labels = {0:'esquerda',1:'centro',2:'bolsominion'}

# Fitting K-Means to the dataset

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters = 3, init = 'random', random_state = 1)
#kmeans = KMeans(n_clusters = 5, init = 'k-means++', random_state = 1)
y_kmeans = kmeans.fit_predict(X)
y2 = kmeans.predict(X)
#print(y_kmeans[:10])
#print(y2[:10])

#print(kmeans.cluster_centers_[0])
#print(kmeans.cluster_centers_[1])
#print(kmeans.cluster_centers_[2])

esquerda = [[0,1,1,0.5,1,1,0,0,0,0.5,0,0,0.5,0.5,0.5]]
bolsominion = [[1,0,0,0,0,0,1,1,1,1,1,0.5,1,1,0.5]]
glauber = [[0.5,0,0.5,0.5,0,1,0.5,0,0.5,0,0.5,0,0,1,1]]
cicero = [[0,1,1,1,1,1,0,0.5,1,1,0.5,0,0,1,1]]
print("\nEsquerda é:",kmeans.predict(esquerda))
print("Bolsominion é:",kmeans.predict(bolsominion))
print("\nGlauber é",labels[kmeans.predict(glauber)[0]])
print("Cicero é",labels[kmeans.predict(cicero)[0]])